apiVersion: v1
kind: Secret
metadata:
  name: spoke-staging-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: spoke-staging
  server: https://spoke-staging-control-plane:6443
  config: |
    {
      "tlsClientConfig": {
        "insecure": true
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: spoke-prod-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: spoke-prod
  server: https://spoke-prod-control-plane:6443
  config: |
    {
      "tlsClientConfig": {
        "insecure": true
      }
    }
